hellomake:
		python tokens.py Test/Test1.txt;
		python tokens.py Test/Test2.txt;
		python tokens.py Test/Test3.txt;
		python tokens.py Test/Test4.txt;
		python tokens.py Test/Test5.txt;
clean:
		rm *.pyc